bashrc-plex: Use shflags to simplify checking writeability

diff --git a/bashrc-plex b/bashrc-plex
--- a/bashrc-plex
+++ b/bashrc-plex
@@ -3,6 +3,16 @@
 ######################################################################
 # Set up for my Plex environment
 
+# Get directory containing this file
+# (This trick was found online.  It won't resolve symlinks.)
+pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null
+SCRIPT_DIR=$PWD
+popd > /dev/null
+
+
+# Use shflags
+. ${SCRIPT_DIR}/shflags
+
 ##
 # Aliases
 
@@ -28,15 +38,34 @@ function demunge { echo $1 | tr ${MY_PATH_SEP} "/"            ; }
 
 # Check that the given file exists and is regular
 function check_file {
-  if [ ! -e $1 ]
+  DEFINE_boolean 'writeable' false 'also check whether file is writable' 'w'
+  FLAGS "$@" || return 1
+  eval set -- "${FLAGS_ARGV}"
+
+  local ret=0
+
+  if [[ $# -eq 0 ]]
+  then
+    echo 'Error: filename missing' >&2
+    flags_help
+    ret=1
+  elif [[ ! -e $1 ]]
   then
     echo $1 does not exist
-    return 1
-  elif [ ! -f $1 ]
+    ret=1
+  elif [[ ! -f $1 ]]
   then
     echo $1 is not a regular file
-    return 1
+    ret=1
+  elif [[ ${FLAGS_writeable} = ${FLAGS_TRUE} && ! -w $1 ]]
+  then
+    echo $1 is not writable
+    ret=1
   fi
+
+  flags_reset
+
+  return ${ret}
 }
 
 # Copy a file from the source tree to the local directory.
@@ -59,19 +88,16 @@ function amove () {
   local munged=$2
   local full_path=$3
 
-  check_file ${full_path} || return 1
   case ${op} in
     push)
-      if [ ! -w ${full_path} ]
-      then
-        echo File ${full_path} is not writable
-        return 1
-      fi
+      check_file -w ${full_path} || return 1          
 
       cp ./${munged} ${full_path}
       ;;
 
     pull)
+      check_file -w ${full_path} || return 1          
+
       cp ${full_path} ./${munged}
       ;;
 
@@ -155,11 +181,6 @@ export PATH=${CLOJURESCRIPT_HOME}/bin:$PATH
 
 VERBOSE=0
 
-# Get directory containing this file
-# (This trick was found online.  It won't resolve symlinks.)
-pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null
-SCRIPT_DIR=$PWD
-popd > /dev/null
 
 BASHRC_COMMON=$SCRIPT_DIR/bashrc-common
 
